# codexskin tray host (generated by `codexskin service install --tray`; do not edit)
# Silent tray icon with Start / Stop / Status / Quit for the watch task.
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$taskId = "codexskin-watch"

$icon = New-Object System.Windows.Forms.NotifyIcon
$icon.Text = "codexskin watch"
$icon.Icon = [System.Drawing.SystemIcons]::Application
$icon.Visible = $true

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$menu.Items.Add("&Start watch", $null, {
    param($sender, $event)
    Start-ScheduledTask -TaskName $taskId -ErrorAction SilentlyContinue
}) | Out-Null
$menu.Items.Add("S&top watch", $null, {
    param($sender, $event)
    Stop-ScheduledTask -TaskName $taskId -ErrorAction SilentlyContinue
}) | Out-Null
$menu.Items.Add("S&tatus", $null, {
    param($sender, $event)
    $t = Get-ScheduledTask -TaskName $taskId -ErrorAction SilentlyContinue
    $state = if ($t) { [string]$t.State } else { "NotInstalled" }
    [System.Windows.Forms.MessageBox]::Show($state, "codexskin watch") | Out-Null
}) | Out-Null
$menu.Items.Add("&Quit tray", $null, {
    param($sender, $event)
    $icon.Visible = $false
    [System.Windows.Forms.Application]::Exit()
}) | Out-Null
$icon.ContextMenuStrip = $menu

$context = New-Object System.Windows.Forms.ApplicationContext
[System.Windows.Forms.Application]::Run($context)
$icon.Dispose()
