# codexskin tray host (generated by codexskin; do not edit)
# Native desktop integration in the style of Codex-Dream-Skin's tray app:
# single instance, context menu, balloon notifications, login autostart.
param(
  [Parameter(Mandatory = $true)][int]$Port,
  [Parameter(Mandatory = $true)][string]$Token,
  [string]$LogFile
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$mutex = [System.Threading.Mutex]::new($false, 'Local\codexskin.tray')
$acquired = $false
try { $acquired = $mutex.WaitOne(0) } catch [System.Threading.AbandonedMutexException] { $acquired = $true }
if (-not $acquired) { exit 0 }

$notify = $null
$icon = $null
function Log([string]$msg) {
  if ($LogFile) { try { Add-Content -LiteralPath $LogFile -Value ("[{0}] {1}" -f (Get-Date -Format o), $msg) } catch {} }
}
function Invoke-Api([string]$route, [string]$Body) {
  try {
    if ($Body) {
      $res = Invoke-RestMethod -Uri ("http://127.0.0.1:{0}/t/{1}/{2}" -f $Port, $Token, $route) -Method Post -ContentType 'application/json' -Body $Body -TimeoutSec 180
    } else {
      $res = Invoke-RestMethod -Uri ("http://127.0.0.1:{0}/t/{1}/{2}" -f $Port, $Token, $route) -Method Post -TimeoutSec 180
    }
    return $res
  } catch {
    Log ("api {0} failed: {1}" -f $route, $_.Exception.Message)
    return $null
  }
}
function Show-Balloon([string]$text, [string]$kind = 'Info') {
  try {
    $tip = [Enum]::Parse([System.Windows.Forms.ToolTipIcon], $kind)
    $notify.ShowBalloonTip(2600, 'codexskin', $text, $tip)
  } catch {}
}

try {
  $notify = [System.Windows.Forms.NotifyIcon]::new()
  try {
    $iconPath = Join-Path $PSScriptRoot 'codexskin-tray.ico'
    $icon = [System.Drawing.Icon]::new($iconPath)
    $notify.Icon = $icon
  } catch {
    $notify.Icon = [System.Drawing.SystemIcons]::Application
  }
  $notify.Text = 'codexskin'
  $notify.Visible = $true

  $menu = [System.Windows.Forms.ContextMenuStrip]::new()
  $notify.ContextMenuStrip = $menu

  $status = $menu.Items.Add('codexskin')
  $status.Enabled = $false
  [void]$menu.Items.Add([System.Windows.Forms.ToolStripSeparator]::new())

  $openwin = $menu.Items.Add('&Open control window')
  $openwin.add_Click({
    $r = Invoke-Api 'open-window' ''
    if ($null -ne $r -and $r.ok -and $r.url) {
      Log 'control window opened'
    }
  })

  $apply = $menu.Items.Add('&Apply / re-apply skin')
  $apply.add_Click({
    $r = Invoke-Api 'apply-active'
    if ($null -ne $r -and $r.ok) {
      $w = if ($r.windows) { $r.windows } else { 1 }
      Show-Balloon ("Skin applied in {0} window(s)." -f $w)
    } elseif ($null -ne $r -and $r.code -eq 'CODEX_RUNNING_NO_PORT') {
      # Codex runs the normal way: skinning needs a restart - ask first,
      # exactly like the reference app's -PromptRestart flow.
      $answer = [System.Windows.Forms.MessageBox]::Show(
        "Codex is running without the skin profile.`n`nRestart it now with the skin applied? (The app will close and reopen automatically.)",
        'codexskin',
        [System.Windows.Forms.MessageBoxButtons]::YesNo,
        [System.Windows.Forms.MessageBoxIcon]::Question)
      if ($answer -eq [System.Windows.Forms.DialogResult]::Yes) {
        $r2 = Invoke-Api 'apply-active' '{"restart":true}'
        if ($null -ne $r2 -and $r2.ok) {
          $w2 = if ($r2.windows) { $r2.windows } else { 1 }
          Show-Balloon ("Skin applied in {0} window(s). Codex restarted with the skin profile." -f $w2)
        } else {
          $err = if ($null -ne $r2) { $r2.error } else { 'UI server unreachable' }
          Show-Balloon ("Apply failed: {0}" -f $err) 'Warning'
        }
      }
    } else {
      $err = if ($null -ne $r) { $r.error } else { 'UI server unreachable' }
      Show-Balloon ("Apply failed: {0}" -f $err) 'Warning'
    }
  })

  $launch = $menu.Items.Add('&Launch skinned Codex')
  $launch.add_Click({
    $r = Invoke-Api 'launch-codex'
    if ($null -ne $r -and $r.ok) {
      $msg = if ($r.launched) { 'Codex started with the skin profile.' } else { 'Codex already running with the skin profile.' }
      Show-Balloon $msg
    } else {
      $err = if ($null -ne $r) { $r.error } else { 'UI server unreachable' }
      Show-Balloon ("Launch failed: {0}" -f $err) 'Warning'
    }
  })

  $restore = $menu.Items.Add('Restore &official look')
  $restore.add_Click({
    $r = Invoke-Api 'restore'
    if ($null -ne $r -and $r.ok -and $r.attempted) { Show-Balloon 'Official look restored.' }
    elseif ($null -ne $r -and $r.ok) { Show-Balloon 'Codex not running; nothing to restore.' }
    else { Show-Balloon 'Restore failed: UI server unreachable' 'Warning' }
  })

  $autostart = $menu.Items.Add('Launch at &login')
  $autostart.CheckOnClick = $true
  $autostart.add_Click({
    if ($script:suppressSync) { return }
    $verb = 'disable'
    if ($autostart.Checked) { $verb = 'enable' }
    $r = Invoke-Api ('autostart/{0}' -f $verb)
    if ($null -ne $r -and $r.ok) {
      $done = 'disabled'
      if ($autostart.Checked) { $done = 'enabled' }
      Show-Balloon ("Launch at login {0}." -f $done)
    } else {
      $err = if ($null -ne $r) { $r.error } else { 'UI server unreachable' }
      Show-Balloon ("Could not change autostart: {0}" -f $err) 'Warning'
      $autostart.Checked = -not $autostart.Checked
    }
  })

  $autorestart = $menu.Items.Add('Auto-restart Codex for the &skin')
  $autorestart.CheckOnClick = $true
  $autorestart.add_Click({
    if ($script:suppressSync) { return }
    $on = $false
    if ($autorestart.Checked) { $on = $true }
    $r = Invoke-Api 'settings/auto-restart' (("{{""enabled"":{0}}}" -f $on.ToString().ToLower()))
    if ($null -ne $r -and $r.ok) {
      $done = 'off'
      if ($on) { $done = 'on' }
      Show-Balloon ("Auto-restart turned {0}." -f $done)
    } else {
      $err = if ($null -ne $r) { $r.error } else { 'UI server unreachable' }
      Show-Balloon ("Could not change auto-restart: {0}" -f $err) 'Warning'
      $autorestart.Checked = -not $autorestart.Checked
    }
  })

  function Show-RestartConsent {
    # Same question the UI window shows; answered once, remembered forever.
    $answer = [System.Windows.Forms.MessageBox]::Show(
      "codexskin noticed Codex running without the skin profile.`n`nAllow codexskin to close and restart Codex with the skin applied whenever it detects a normal launch? (You will not be asked again; you can change this anytime in the menu.)",
      'codexskin',
      [System.Windows.Forms.MessageBoxButtons]::YesNo,
      [System.Windows.Forms.MessageBoxIcon]::Question)
    $allow = $false
    if ($answer -eq [System.Windows.Forms.DialogResult]::Yes) { $allow = $true }
    $r = Invoke-Api 'consent/restart' (("{{""allow"":{0}}}" -f $allow.ToString().ToLower()))
    if ($null -ne $r -and $r.ok) {
      if ($allow) { Show-Balloon 'Thanks - the skin will stay on automatically.' }
      else { Show-Balloon 'Auto-restart declined.' 'Warning' }
    }
  }

  $quit = $menu.Items.Add('&Quit codexskin')
  $quit.add_Click({
    $null = Invoke-Api 'quit'
    $notify.Visible = $false
    [System.Windows.Forms.Application]::Exit()
  })

  # Watchdog: when the UI server stays unreachable, exit - a crashed or
  # quit main app must not leave a dead tray behind.
  $script:serverFails = 0
  $watch = New-Object System.Windows.Forms.Timer
  $watch.Interval = 5000
  $watch.add_Tick({
    try {
      $null = Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:{0}/t/{1}/ping" -f $Port, $Token) -TimeoutSec 3
      $script:serverFails = 0
    } catch {
      $script:serverFails = $script:serverFails + 1
      if ($script:serverFails -ge 3) {
        Log 'UI server unreachable; tray exiting'
        $notify.Visible = $false
        [System.Windows.Forms.Application]::Exit()
      }
    }
  })
  $watch.Start()

  # State poll: keep the two checkable menu items in sync with settings
  # changed elsewhere (UI window checkboxes), without clobbering clicks.
  $script:suppressSync = $true
  $statePoll = New-Object System.Windows.Forms.Timer
  $statePoll.Interval = 8000
  $statePoll.add_Tick({
    try {
      $s = Invoke-RestMethod -Uri ("http://127.0.0.1:{0}/t/{1}/state" -f $Port, $Token) -TimeoutSec 4
      $script:suppressSync = $true
      try {
        $autostart.Checked = [bool]$s.autostartEnabled
        $autorestart.Checked = [bool]$s.autoRestartEnabled
      } finally {
        $script:suppressSync = $false
      }
    } catch {}
  })
  $statePoll.Start()

  # Consent poll: surface the watcher's restart-consent ask as a MessageBox.
  $consentPoll = New-Object System.Windows.Forms.Timer
  $consentPoll.Interval = 5000
  $consentPoll.add_Tick({
    try {
      $c = Invoke-RestMethod -Uri ("http://127.0.0.1:{0}/t/{1}/consent/restart" -f $Port, $Token) -Method Get -TimeoutSec 4
      if ($null -ne $c -and $c.ok -and $null -ne $c.pending) { Show-RestartConsent }
    } catch {}
  })
  $consentPoll.Start()

  # Double-click opens the control window (reference app behavior).
  $notify.add_DoubleClick({
    $r = Invoke-Api 'open-window' ''
    if ($null -ne $r -and $r.ok -and $r.url) {
      Log 'control window opened'
    }
  })

  Log 'tray host started'
  [System.Windows.Forms.Application]::Run([System.Windows.Forms.ApplicationContext]::new())
} finally {
  if ($null -ne $notify) { $notify.Dispose() }
  if ($null -ne $icon) { $icon.Dispose() }
  if ($acquired) { try { $mutex.ReleaseMutex() } catch {} }
  $mutex.Dispose()
  Log 'tray host stopped'
}
